# Generated by Django 4.2 on 2023-05-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_order_customer_order_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="tag",
            field=models.ManyToManyField(to="crm.tag"),
        ),
    ]
