# Generated by Django 4.2 on 2023-05-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_tag_order_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="tag",
            new_name="tags",
        ),
    ]
