# Generated by Django 4.2 on 2023-05-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_rename_tag_order_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="tags",
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="crm.tag"),
        ),
    ]
